services:
  web:
    image: maintenance_planner
    build: .
    command: gunicorn --bind=0.0.0.0:8000 MaintenancePlanner.wsgi:application
    volumes:
      - /tmp/app-resources/static:/app/static
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - .env
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: maintenance_planner_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - /tmp/for_deploy/static:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web
