# Generated by Django 4.2.3 on 2023-07-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Measuring tool', 'Measuring tool'), ('Hand power tool', 'Hand power tool')], max_length=30),
        ),
    ]
